### ISSUE TITLE
Quasar daemon chracshes on windows

### ISSUE THREAD

**Issue by roamingman** [scakemyer/quasar#20]
It started crashing two days ago. Installing the new release quasar-0.9.35 did not help.
Here is the kodi log where it fails

```
08:42:13 T:9996  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
08:42:13 T:9996  NOTICE: [plugin.video.quasar] [signal 0xc0000005 code=0x0 addr=0x0 pc=0x560893]
08:42:13 T:9996  NOTICE: [plugin.video.quasar]
08:42:13 T:9996  NOTICE: [plugin.video.quasar] goroutine 1 [running]:
08:42:13 T:9996  NOTICE: [plugin.video.quasar] panic(0xa0f1a0, 0xc0420040b0)
08:42:13 T:9996  NOTICE: [plugin.video.quasar]  /usr/local/go/src/runtime/panic.go:500 +0x1af
08:42:13 T:9996  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/xbmc.executeJSONRPCEx(0xab9d5b, 0xc, 0x9bf880, 0xc042216000, 0x0, 0x0, 0x0, 0x0, 0x0)
08:42:13 T:9996  NOTICE: [plugin.video.quasar]  /go/src/github.com/scakemyer/quasar/xbmc/jsonrpc.go:62 +0xd3
08:42:13 T:9996  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/xbmc.GetAddonInfo(0xc042006600)
08:42:13 T:9996  NOTICE: [plugin.video.quasar]  /go/src/github.com/scakemyer/quasar/xbmc/xbmcaddon.go:24 +0xa8
08:42:13 T:9996  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/config.Reload(0xc0420079b0)
08:42:13 T:9996  NOTICE: [plugin.video.quasar]  /go/src/github.com/scakemyer/quasar/config/config.go:82 +0xfd
08:42:13 T:9996  NOTICE: [plugin.video.quasar] main.main()
08:42:13 T:9996  NOTICE: [plugin.video.quasar]  /go/src/github.com/scakemyer/quasar/main.go:84 +0x491
08:42:13 T:9996  NOTICE: [plugin.video.quasar]
08:42:13 T:9996  NOTICE: Previous line repeats 85 times.
08:42:13 T:9996  NOTICE: [plugin.video.quasar] System information: windows_x64 post2012Server
08:42:13 T:9996  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:20160424-c327c53
08:42:13 T:9996  NOTICE: [plugin.video.quasar] OS type: Windows
08:42:13 T:9996  NOTICE: [plugin.video.quasar] uname: ('Windows', 'JOHNDL', 'post2012Server', '6.3.9600', 'AMD64', 'Intel64 Family 6 Model 55 Stepping 8, GenuineIntel')
08:42:14 T:11044  NOTICE: EPG::CEpgContainer::Start - EPG thread started
08:42:15 T:10492   ERROR: C:\Users\Owner.JOHNDL\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
08:42:16 T:9996  NOTICE: [plugin.video.quasar] quasard: starting quasard
08:42:18 T:9996  NOTICE: [plugin.video.quasar] Deleting stale files set([])
```

**Comment by scakemyer** [comment]
Looks like a port conflict, you probably have another Quasar process still running.

**Comment by RosenMonov** [comment]
Close this issue: I found a solution: after resdtarting the OS, the issue get fixed. The reason is that in contrast with all kodi sctipts, Quasar runs its own executable (tread), and closing kodi does not stop it. Same solution  worked for Android.
